# https://cloud.google.com/appengine/docs/flexible/nodejs/reference/app-yaml
runtime: nodejs
env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cpu_utilization:
    target_utilization: 0.75
handlers:
  - url: .*
    script: auto
    secure: always
